name: Daily Update

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 8:30 AM IST (3:00 UTC)
  workflow_dispatch:     # Allows manual run from GitHub Actions UI

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Use your Personal Access Token

      - name: Update Timestamp
        run: |
          echo "<!-- Last updated: $(date -u) -->" > timestamp.html
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add timestamp.html
          git commit -m "Daily update $(date -u)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
